name: 🚀 Deploy website on push
on:
  push:
    branches: [main]
jobs:
  job_one:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      name: test ssh connect
      uses: appleboy/ssh-action@master
      with:
        host: 46.175.145.70
        username: o251298
        key: ${{ secrets.OMG_SECRET }}
        port: 22
        script: |
          cd deploy
          git pull origin main
          git status